kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: carrera-api
namePrefix: carrera-
resources:
- deployment.yaml
- service.yaml
<<<<<<< HEAD
# - ingress.yaml
=======
#- ingress.yaml
>>>>>>> ci-84/add-k8s-deployment
