kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: carrera-api
namePrefix: carrera-
resources:
- deployment.yaml
- service.yaml
images:
- name: carrera-api
  newName: gcr.io/devopspatterns/api
  newTag: 3f2eb9ddd18a6ab92d6518e0479fecd33b8043df.1563823861
