kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: carrera-api
namePrefix: carrera-
resources:
- deployment.yaml
- service.yaml
images:
- name: carrera-api
  newName: gcr.io/devopspatterns/carrera-api
  newTag: 62aa76d.1563526504
